# Generated by Django 4.2.3 on 2023-12-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0004_alter_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
