# Generated by Django 4.2.3 on 2023-12-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0006_posts_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upComingEvents',
        ),
    ]
