# Generated by Django 4.2.3 on 2023-12-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0007_delete_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='upComingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='upcoming/image')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10)),
                ('address', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
