# Generated by Django 4.2.3 on 2023-12-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0009_event_detail_page_alter_upcomingevents_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_detail_page',
        ),
    ]
