# Generated by Django 4.2.3 on 2023-12-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0011_event_detail_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_detail_page',
        ),
    ]
