# Generated by Django 4.2.3 on 2023-12-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0016_create_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_group',
        ),
    ]
